---
- hosts: routers
  gather_facts: no
  connection: local

  tasks:
  - name: Include Login Credentials
    include_vars: secrets.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

  - name: SHOW CONFIG
      provider: "{{ provider }}"
      commands:
        - show run
    register: run
  - name: show run
    copy: content="{{ run.stdout[0] }}" dest="/etc/ansible/routerconfig/{{ inventory_hostname }}.txt"
    
