---
- hosts: routers
  gather_facts: no
  connection: local

  tasks:
  - name: Include Login Credentials
    include_vars: secrets.yml

  - name: Define Provider
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

  - name: RUN 'Show Clock'
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show clock
    register: clock
  - name: print output
    debug: msg={{ clock.stdout_lines }}

